version: '3.8'

services:
  webmuscat:
    container_name: webmuscat
    build:
      dockerfile: ./Dockerfile
    volumes:
      - /websites/muscatdata:/usr/local/MuscatFX/src/muscat/data
    ports:
      - 127.0.0.1:8091:80
    restart: always
